name: Publish documentation
on:
  push:
    tags: 
    - '**'

jobs:
  build:
    concurrency: docs-publisher
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: lerna bootstrap
    - uses: marcoreni/docs-publisher-action@v0.1.0-alpha.5
      with:
        deployment-branch: 'gh-pages'
        docs-command: 'lerna run --scope {packageName} docs'
        docs-path: 'packages/{packageNameWithoutScope}/docs'
        strategy: 'lerna'
