name: Test prepareenv

on:
  workflow_dispatch:
    inputs:
      build_environment:
        description: 'Environment to be used. Choose between "testenv1", "testenv2"'
        required: true
  # schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '0/10 * * * *'

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    env:
      # Set here the default environment. It will be used for scheduled jobs
      DEFAULT_BUILD_ENVIRONMENT: 'testenv1'
    steps:
      - id: setenv
        run: echo '::set-output name=environment::${{ github.event.inputs.build_environment || env.DEFAULT_BUILD_ENVIRONMENT }}' 
    outputs:
      # If you need to reference the environment, you can use needs.prepare-env.outputs.build_environment
      build_environment: ${{ steps.setenv.outputs.environment }}

  build:
    
    needs: prepare-env
    runs-on: ubuntu-latest
    environment: ${{ needs.prepare-env.outputs.build_environment }}
    env:
      BUILD_ENVIRONMENT: ${{ needs.prepare-env.outputs.build_environment }}
    steps:
    - id: check
      run: |
        export MATCH_LENGTH=$(curl -sL  -H "Authorization: bearer ${TEST_TOKEN}" https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?event=schedule  | jq -r "[.workflow_runs[] | select(.head_sha == \"${CURRENT_SHA}\")] | length")
        echo "::set-output name=match_length::${MATCH_LENGTH}"
        echo "The match length is ${MATCH_LENGTH}"
